server.port=${SERVER_PORT:8080}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/quickmeds?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Ritu222003@}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=mysecretkeymysecretkeymysecretkey12
app.jwt.expiration-ms=86400000

app.upload-dir=uploads
app.frontend-url=http://127.0.0.1:5173

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB