-- PostgreSQL startup seed for QuickMeds
-- Runs automatically when spring.sql.init.mode=always

INSERT INTO categories (id, name, description) VALUES
  (1, 'Pain Relief', 'Pain and inflammation medicines'),
  (2, 'Antibiotics', 'Bacterial infection treatment'),
  (3, 'Cold & Flu', 'Cold and fever care'),
  (4, 'Vitamins & Supplements', 'Daily health supplements'),
  (5, 'Digestive Health', 'Digestive health medicines')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description;

INSERT INTO medicines (id, name, description, price, stock, requires_prescription, dosage, image_url, category_id) VALUES
  (1, 'Dolo 650', 'Used to reduce fever and mild body pain | Generic: Paracetamol | Manufacturer: Sun Pharma', 54.00, 78, false, '650 mg', NULL, 1),
  (2, 'Crocin Advance', 'Provides quick relief from fever and headache | Generic: Paracetamol | Manufacturer: Cipla', 48.00, 64, false, '500 mg', NULL, 1),
  (3, 'Combiflam', 'Relieves pain inflammation and fever | Generic: Ibuprofen + Paracetamol | Manufacturer: Dr. Reddys', 72.00, 43, false, '400mg+325mg', NULL, 1),
  (4, 'Saridon', 'Effective for tension headache relief | Generic: Propyphenazone + Paracetamol + Caffeine | Manufacturer: Lupin', 68.00, 57, false, '350mg+150mg+50mg', NULL, 1),
  (5, 'Voveran SR', 'Used for joint pain and swelling relief | Generic: Diclofenac Sodium | Manufacturer: Zydus', 116.00, 35, false, '100 mg', NULL, 1),
  (6, 'Zerodol SP', 'Reduces musculoskeletal pain | Generic: Aceclofenac + Paracetamol + Serratiopeptidase | Manufacturer: Sun Pharma', 162.00, 29, false, '100mg+325mg+15mg', NULL, 1),
  (7, 'Meftal Spas', 'Used for abdominal cramps | Generic: Mefenamic Acid + Dicyclomine | Manufacturer: Cipla', 138.00, 41, false, '250mg+10mg', NULL, 1),
  (8, 'Ultracet', 'Used for severe pain | Generic: Tramadol + Paracetamol | Manufacturer: Dr. Reddys', 182.00, 22, true, '37.5mg+325mg', NULL, 1),
  (9, 'Calpol 500', 'Relieves fever and pain | Generic: Paracetamol | Manufacturer: Lupin', 44.00, 88, false, '500 mg', NULL, 1),
  (10, 'Brufen 400', 'Used for inflammation and pain | Generic: Ibuprofen | Manufacturer: Zydus', 58.00, 53, false, '400 mg', NULL, 1),
  (11, 'Nise', 'Relieves pain and inflammation | Generic: Nimesulide | Manufacturer: Sun Pharma', 82.00, 48, false, '100 mg', NULL, 1),
  (12, 'Flexon', 'Used for fever and pain | Generic: Ibuprofen + Paracetamol | Manufacturer: Cipla', 66.00, 55, false, '400mg+325mg', NULL, 1),
  (13, 'Myospaz', 'Muscle relaxant | Generic: Chlorzoxazone + Paracetamol | Manufacturer: Dr. Reddys', 158.00, 33, true, '250mg+325mg', NULL, 1),
  (14, 'Nucoxia 90', 'Used for arthritis | Generic: Etoricoxib | Manufacturer: Zydus', 176.00, 28, true, '90 mg', NULL, 1),
  (15, 'Tramazac', 'Moderate to severe pain | Generic: Tramadol | Manufacturer: Lupin', 198.00, 22, true, '50 mg', NULL, 1),
  (16, 'Azithral 500', 'Treats bacterial infections | Generic: Azithromycin | Manufacturer: Sun Pharma', 139.00, 32, true, '500 mg', NULL, 2),
  (17, 'Augmentin 625', 'Broad spectrum antibiotic | Generic: Amoxicillin + Clavulanic Acid | Manufacturer: Cipla', 218.00, 27, true, '500mg+125mg', NULL, 2),
  (18, 'Cifran 500', 'UTI and GI infections | Generic: Ciprofloxacin | Manufacturer: Dr. Reddys', 106.00, 46, true, '500 mg', NULL, 2),
  (19, 'Taxim-O 200', 'Respiratory infections | Generic: Cefixime | Manufacturer: Lupin', 162.00, 34, true, '200 mg', NULL, 2),
  (20, 'Azee 500', 'ENT infections | Generic: Azithromycin | Manufacturer: Zydus', 132.00, 39, true, '500 mg', NULL, 2),
  (21, 'Moxikind-CV 625', 'Chest infections | Generic: Amoxicillin + Clavulanic Acid | Manufacturer: Sun Pharma', 196.00, 25, true, '500mg+125mg', NULL, 2),
  (22, 'O2 Tablet', 'Mixed infections | Generic: Ofloxacin + Ornidazole | Manufacturer: Cipla', 188.00, 31, true, '200mg+500mg', NULL, 2),
  (23, 'Doxy-1 L-DR', 'Skin infections | Generic: Doxycycline | Manufacturer: Dr. Reddys', 94.00, 55, true, '100 mg', NULL, 2),
  (24, 'Levoflox 500', 'Severe infections | Generic: Levofloxacin | Manufacturer: Lupin', 149.00, 37, true, '500 mg', NULL, 2),
  (25, 'Monocef-O 200', 'Lung infections | Generic: Cefpodoxime | Manufacturer: Zydus', 174.00, 28, true, '200 mg', NULL, 2),
  (26, 'Clavam 625', 'Respiratory infections | Generic: Amoxicillin + Clavulanic Acid | Manufacturer: Sun Pharma', 202.00, 29, true, '625 mg', NULL, 2),
  (27, 'Floxip', 'GI infections | Generic: Ciprofloxacin | Manufacturer: Cipla', 114.00, 41, true, '500 mg', NULL, 2),
  (28, 'Redixime 200', 'Lung infections | Generic: Cefixime | Manufacturer: Dr. Reddys', 154.00, 37, true, '200 mg', NULL, 2),
  (29, 'Azicip 500', 'Throat infections | Generic: Azithromycin | Manufacturer: Lupin', 128.00, 36, true, '500 mg', NULL, 2),
  (30, 'Lariago', 'Malaria treatment | Generic: Chloroquine | Manufacturer: Zydus', 84.00, 52, true, '250 mg', NULL, 2),
  (31, 'Cetcip', 'Relieves allergies | Generic: Cetirizine | Manufacturer: Sun Pharma', 52.00, 69, false, '10 mg', NULL, 3),
  (32, 'Okacet', 'Allergy relief | Generic: Cetirizine | Manufacturer: Cipla', 46.00, 73, false, '10 mg', NULL, 3),
  (33, 'Sinarest', 'Cold and fever relief | Generic: Cold Combo | Manufacturer: Dr. Reddys', 78.00, 48, false, NULL, NULL, 3),
  (34, 'Vicks Action 500', 'Cold symptoms | Generic: Cold Combo | Manufacturer: Lupin', 64.00, 62, false, NULL, NULL, 3),
  (35, 'Cheston Cold', 'Cold management | Generic: Cold Combo | Manufacturer: Zydus', 69.00, 51, false, NULL, NULL, 3),
  (36, 'Benadryl', 'Cough relief | Generic: Dextromethorphan | Manufacturer: Sun Pharma', 112.00, 36, false, '100 ml syrup', NULL, 3),
  (37, 'Ascoril LS', 'Chest congestion | Generic: Ambroxol Combo | Manufacturer: Cipla', 129.00, 33, false, '100 ml syrup', NULL, 3),
  (38, 'Alex Lozenges', 'Sore throat relief | Generic: Hexylresorcinol | Manufacturer: Dr. Reddys', 55.00, 82, false, '2.4 mg', NULL, 3),
  (39, 'Honitus', 'Herbal cough syrup | Generic: Herbal | Manufacturer: Lupin', 135.00, 40, false, '100 ml syrup', NULL, 3),
  (40, 'Wikoryl', 'Cold symptoms | Generic: Cold Combo | Manufacturer: Zydus', 67.00, 58, false, NULL, NULL, 3),
  (41, 'Allegra 120', 'Allergy relief | Generic: Fexofenadine | Manufacturer: Sun Pharma', 98.00, 63, false, '120 mg', NULL, 3),
  (42, 'Montair LC', 'Allergy treatment | Generic: Montelukast + Levocetirizine | Manufacturer: Cipla', 162.00, 45, false, '10mg+5mg', NULL, 3),
  (43, 'Grilinctus', 'Cough suppressant | Generic: Dextromethorphan | Manufacturer: Dr. Reddys', 146.00, 39, false, '100 ml syrup', NULL, 3),
  (44, 'TusQ', 'Severe cough | Generic: Codeine Syrup | Manufacturer: Lupin', 158.00, 28, true, '100 ml syrup', NULL, 3),
  (45, 'Kofol', 'Ayurvedic cough relief | Generic: Herbal | Manufacturer: Zydus', 118.00, 44, false, '100 ml syrup', NULL, 3),
  (46, 'Becosules', 'Vitamin deficiency | Generic: B Complex | Manufacturer: Sun Pharma', 72.00, 76, false, NULL, NULL, 4),
  (47, 'Shelcal 500', 'Bone health | Generic: Calcium + D3 | Manufacturer: Cipla', 158.00, 45, false, '500 mg', NULL, 4),
  (48, 'Revital H', 'Energy supplement | Generic: Multivitamin | Manufacturer: Dr. Reddys', 340.00, 30, false, NULL, NULL, 4),
  (49, 'Neurobion Forte', 'Nerve health | Generic: B Complex | Manufacturer: Lupin', 62.00, 66, false, NULL, NULL, 4),
  (50, 'Limcee 500', 'Immunity booster | Generic: Vitamin C | Manufacturer: Zydus', 48.00, 90, false, '500 mg', NULL, 4),
  (51, 'Zincovit', 'Immunity support | Generic: Multivitamin | Manufacturer: Sun Pharma', 138.00, 54, false, NULL, NULL, 4),
  (52, 'Supradyn', 'Daily supplement | Generic: Multivitamin | Manufacturer: Cipla', 182.00, 47, false, NULL, NULL, 4),
  (53, 'Evion 400', 'Skin health | Generic: Vitamin E | Manufacturer: Dr. Reddys', 56.00, 71, false, '400 mg', NULL, 4),
  (54, 'A to Z NS', 'Nutrition support | Generic: Multivitamin | Manufacturer: Lupin', 114.00, 59, false, NULL, NULL, 4),
  (55, 'Livogen', 'Anemia treatment | Generic: Iron + Folic Acid | Manufacturer: Zydus', 146.00, 38, false, NULL, NULL, 4),
  (56, 'Digene Gel', 'Acidity relief | Generic: Antacid | Manufacturer: Sun Pharma', 165.00, 44, false, '200 ml', NULL, 5),
  (57, 'ENO', 'Quick acidity relief | Generic: Sodium Bicarbonate | Manufacturer: Cipla', 32.00, 96, false, NULL, NULL, 5),
  (58, 'Gelusil', 'Bloating relief | Generic: Antacid | Manufacturer: Dr. Reddys', 138.00, 49, false, NULL, NULL, 5),
  (59, 'Pudin Hara', 'Gas relief | Generic: Peppermint Oil | Manufacturer: Lupin', 46.00, 84, false, NULL, NULL, 5),
  (60, 'Pan D', 'Acidity control | Generic: Pantoprazole + Domperidone | Manufacturer: Zydus', 192.00, 27, true, '40mg+10mg', NULL, 5),
  (61, 'Pantocid 40', 'Acid reflux | Generic: Pantoprazole | Manufacturer: Sun Pharma', 128.00, 42, true, '40 mg', NULL, 5),
  (62, 'Emoz 40', 'Ulcer treatment | Generic: Esomeprazole | Manufacturer: Cipla', 152.00, 36, true, '40 mg', NULL, 5),
  (63, 'Cyclopam', 'Stomach cramps | Generic: Dicyclomine | Manufacturer: Dr. Reddys', 74.00, 63, false, '20 mg', NULL, 5),
  (64, 'Cremaffin', 'Constipation relief | Generic: Laxative | Manufacturer: Lupin', 196.00, 24, false, '200 ml', NULL, 5),
  (65, 'Electral ORS', 'Dehydration | Generic: ORS | Manufacturer: Zydus', 42.00, 87, false, NULL, NULL, 5),
  (66, 'Rantac 150', 'Acid reducer | Generic: Ranitidine | Manufacturer: Sun Pharma', 54.00, 66, false, '150 mg', NULL, 5),
  (67, 'Looz Syrup', 'Constipation | Generic: Lactulose | Manufacturer: Cipla', 162.00, 36, false, '100 ml', NULL, 5)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  stock = EXCLUDED.stock,
  requires_prescription = EXCLUDED.requires_prescription,
  dosage = EXCLUDED.dosage,
  image_url = EXCLUDED.image_url,
  category_id = EXCLUDED.category_id;

SELECT setval(pg_get_serial_sequence('categories', 'id'), COALESCE((SELECT MAX(id) FROM categories), 1), true);
SELECT setval(pg_get_serial_sequence('medicines', 'id'), COALESCE((SELECT MAX(id) FROM medicines), 1), true);
